### ISSUE TITLE
issue with curl posting data format

### ISSUE THREAD

**Issue by Weugene** [soumilshah1995/PythonLambdaDockerECR#1]
Hello!
There is an issue with the posting of JSON data format.
`{"errorMessage": "Unable to unmarshal input: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)", "errorType": "Runtime.UnmarshalError", "requestId": "66882b87-4e50-4cf9-9c60-39e1884d53ae", "stackTrace": []}`

It can be fixed by:
`curl -XPOST "http://localhost:9000/2015-03-31/functions/function/invocations" -d "{\"msg\":\"hello\"}"`

BR,
Evgenii Sharaborin

**Comment by soumilshah1995** [comment]
Thanks i fixed the readme :D
